### ISSUE TITLE
感谢分享EFI，应该 Update MacOS to Catalina 10.15.4 本身系统事情。Close问题了。

### ISSUE THREAD

**Issue by liangyimingcom** [webleon/Hackintosh-OptiPlex-7070-SFF#1]
感谢分享EFI，应该 Update MacOS to Catalina 10.15.4 本身系统事情。Close问题了。

**Comment by webleon** [comment]
没有看到具体的报错信息，猜测可能的问题是光驱的能源管理冲突导致的。
最好能把报错信息完整贴出，更容易定位问题。

**Comment by liangyimingcom** [comment]
谢谢，我的重启问题如下。今天重启了3次，都是不操作了关屏幕的时候；

panic(cpu 4 caller 0xffffff7f8e4eaad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since load (14700 seconds ago): 1471, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since load (14670 seconds ago): 1455, last successful checkin: 120 seconds ago

Backtrace (CPU 4), Frame : Return Address
0xffffff83b2cd3720 : 0xffffff800d3215cd 
0xffffff83b2cd3770 : 0xffffff800d45a3c5 
0xffffff83b2cd37b0 : 0xffffff800d44bf7e 
0xffffff83b2cd3800 : 0xffffff800d2c7a40 
0xffffff83b2cd3820 : 0xffffff800d320c97 
0xffffff83b2cd3920 : 0xffffff800d321087 
0xffffff83b2cd3970 : 0xffffff800dac2ce8 
0xffffff83b2cd39e0 : 0xffffff7f8e4eaad5 
0xffffff83b2cd39f0 : 0xffffff7f8e4ea7fa 
0xffffff83b2cd3a10 : 0xffffff800da54f3e 
0xffffff83b2cd3a60 : 0xffffff7f8e4e9cfe 
0xffffff83b2cd3b60 : 0xffffff800da5e163 
0xffffff83b2cd3ca0 : 0xffffff800d409bb2 
0xffffff83b2cd3db0 : 0xffffff800d327328 
0xffffff83b2cd3e10 : 0xffffff800d2fdcc5 
0xffffff83b2cd3e70 : 0xffffff800d314aa2 
0xffffff83b2cd3f00 : 0xffffff800d432605 
0xffffff83b2cd3fa0 : 0xffffff800d2c8226 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[99A75EFF-7734-31A0-80BF-FF8288E30D9B]@0xffffff7f8e4e9000->0xffffff7f8e4f1fff

BSD process name corresponding to current thread: watchdogd
Boot args: "Kernel=/System/Library/Kernels/kernel" 

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000d000000
Kernel text base: 0xffffff800d200000
__HIB  text base: 0xffffff800d100000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 14721467191151
last loaded kext at 148663593094: @filesystems.smbfs	3.4.2 (addr 0xffffff7f90488000, size 454656)
last unloaded kext at 14033947741671: >!AXsanScheme	3 (addr 0xffffff7f90a56000, size 40960)
loaded kexts:
com.getdropbox.dropbox.kext	1.11.0
com.paragon-software.filesystems.ntfs	71.5.15
com.intel.driver.EnergyDriver	3.5.5
as.acidanthera.BrcmPatchRAM3	2.5.1
com.insanelymac.!IMausiEthernet	2.4.1d1
as.lvs1974.AirportBrcmFixup	2.0.6
as.vit9696.!AALC	1.4.7
as.acidanthera.BrcmFirmwareStore	2.5.1
org.slice.!ICPUMonitor	1.2.3
org.slice.SMIMonitor	1.1.0
org.netkas.FakeSMC	3.5.3
com.rehabman.driver.USBInjectAll	0.7.4
as.vit9696.WhateverGreen	1.3.7
as.vit9696.Lilu	1.4.2
@filesystems.smbfs	3.4.2
@fileutil	20.036.15
@filesystems.autofs	3.0
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.11
>!AHDA	283.15
>!A!IKBLGraphics	14.0.5
>!AGraphicsDevicePolicy	5.1.16
>eficheck	1
>AudioAUUC	1.70
>!A16X50ACPI	3.2
@AGDCPluginDisplayMetrics	5.1.16
>!A!ICFLGraphicsFramebuffer	14.0.5
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.4f6
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!ISlowAdaptiveClocking	4.0.0
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.101.1
>AirPort.Brcm4360	1400.1.1
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	341.0.2
@private.KextAudit	1.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
|IOAVB!F	840.3
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
>!ASMBus!C	1.0.18d1
|IOSMBus!F	1.1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AHDA!C	283.15
|IOHDA!F	283.15
>!AGraphicsControl	5.1.16
|IONDRVSupport	575.1
>!A16X50Serial	3.2
|IOAccelerator!F2	438.4.5
>!ASSE	1.0
@!AGPUWrangler	5.1.16
@!AGraphicsDeviceControl	5.1.16
|IOGraphics!F	575.1
|IOSlowAdaptiveClocking!F	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!UAudio	322.2
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	7.0.4f6
|IO!BHost!CUSBTransport	7.0.4f6
|IO!BHost!CTransport	7.0.4f6
|IO!B!F	7.0.4f6
|IO!BPacketLogger	7.0.4f6
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOAHCIBlock!S	316.100.5
|IONVMe!F	2.1.0
|IOSkywalk!F	1
|IOAHCI!F	290.0.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.101.1
|IOSCSIBlockCommandsDevice	422.101.1
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.101.3
|IOSCSIArchitectureModel!F	422.101.1
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by liangyimingcom** [comment]
https://forums.macrumors.com/threads/constant-kernel-panics-userspace-watchdog-timeout-no-successful-checkins-from-com-apple-windowserver.2222878/

这个帖子有关系。

**Comment by webleon** [comment]
报错信息里面，没有指向一个比较明确的引导问题，所以我暂时也没办法给特别明确的答案。

看了你发的链接， 看起来是一个白苹果也有的问题，我跳着看了几个回复，可能的解决方案是用比较好的DP线，直接通过DP口连接显示器。

**Comment by liangyimingcom** [comment]
感谢您的 investigation，我用2个DP端口连接2台4K显示器。和新版本是有关系，因为上一个版本Version10.15.3没有重启的这么厉害。

**对了，开始报错和PowerState有关系了，请您看一眼给点建议，谢谢🙏。**

panic(cpu 2 caller 0xffffff800f416487): "AppleIntelFramebuffer::setPowerState(0xffffff83519b1000 : 0xffffff7f901a1d88, 2 -> 1) timed out after 45466 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.101.6/iokit/Kernel/IOServicePM.cpp:5296
Backtrace (CPU 2), Frame : Return Address
0xffffff83b1fc3b40 : 0xffffff800ed215cd 
0xffffff83b1fc3b90 : 0xffffff800ee5a3c5 
0xffffff83b1fc3bd0 : 0xffffff800ee4bf7e 
0xffffff83b1fc3c20 : 0xffffff800ecc7a40 
0xffffff83b1fc3c40 : 0xffffff800ed20c97 
0xffffff83b1fc3d40 : 0xffffff800ed21087 
0xffffff83b1fc3d90 : 0xffffff800f4c2c7c 
0xffffff83b1fc3e00 : 0xffffff800f416487 
0xffffff83b1fc3e50 : 0xffffff800f415d69 
0xffffff83b1fc3e60 : 0xffffff800f42d2fe 
0xffffff83b1fc3ea0 : 0xffffff800f414b18 
0xffffff83b1fc3ec0 : 0xffffff800ed63545 
0xffffff83b1fc3f40 : 0xffffff800ed63071 
0xffffff83b1fc3fa0 : 0xffffff800ecc713e 

BSD process name corresponding to current thread: kernel_task
Boot args: "Kernel=/System/Library/Kernels/kernel" 

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000ea00000
Kernel text base: 0xffffff800ec00000
__HIB  text base: 0xffffff800eb00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

**Comment by webleon** [comment]
搜了下，白苹果升级以后也有很多人出现了这个问题，可能是新增HDR功能造成的影响。
目前没有好的解决办法。
我自己没有遇到这样的问题，看了下跟Github上的版本最大的区别是，Clover版本升级到了5108。
