### ISSUE TITLE
进入opencore引导后，出现苹果进度条后，无限重启

### ISSUE THREAD

**Issue by xzxxzx401** [webleon/Hackintosh-OptiPlex-7070-SFF#11]
你好，我是从出厂的7070SFF（无独显）开始安装，Readme中的两个optional是否需要在windows中完成？

如果不改显存64MB和解锁CFGLock，配置需要变化么？

我这边现在安装会在OC引导完，进入安装程序（第一次的苹果图标）的时候重启，不知道跟显存orCFGLock是否有关系？

**Comment by xzxxzx401** [comment]
已解决，显存64MB是必须的，先修改64MB缓存即可避免无限重启。

**Comment by aya4dw** [comment]
Advised to remove "Optional" in "BIOS Settings via GRUB (Optional)", it's sure the computer would restart if do not Setup BIOS via GRUB.

**Comment by webleon** [comment]
> Advised to remove "Optional" in "BIOS Settings via GRUB (Optional)", it's sure the computer would restart if do not Setup BIOS via GRUB.

Good Advise, thanks.
