### ISSUE TITLE
The type of RX560 card

### ISSUE THREAD

**Issue by aya4dw** [webleon/Hackintosh-OptiPlex-7070-SFF#12]
May I ask what type of RX560 card do you use？

**Comment by webleon** [comment]
I use  a Low-Profile Card from Sparklevga.
http://www.sparklevga.com.cn/index.php/product/43.html

**Comment by aya4dw** [comment]
Does your computer keep blackscreen until start into the MacOS?

**Comment by webleon** [comment]
> Does your computer keep blackscreen until start into the MacOS?

No, everything looks good during the booting process. 
The blackscreen problem can be caused by the vBios of the graphic cards, some of vbios not support UEFI.
You can enable legacy boot in Dell bios to see if that can solve.

**Comment by aya4dw** [comment]
Thank you so much!
I added efi to the vbios, and it displayed almost perfect except 0.5s greenscreen when the computer started.
