### ISSUE TITLE
7070mff机器睡眠唤醒后显示器不亮

### ISSUE THREAD

**Issue by lrgcx** [webleon/Hackintosh-OptiPlex-7070-SFF#13]
首先谢谢大佬的分享！我的7070mff换了DW1560网卡，一直用的大佬的efi文件，添加过一些驱动文件，一直到11.4都没问题，bios里关闭了深度睡眠。升级11.5.1后开启深度睡眠，其他都还好，usb也定制过，就是睡眠唤醒后机器已经唤醒但是显示器不亮。不知道是哪里的问题？要是大佬能同时出个7070mff的efi就好了。

**Comment by webleon** [comment]
https://github.com/webleon/Hackintosh-OptiPlex-7060-MFF

**Comment by lrgcx** [comment]
谢谢回复！不知11.5.1安装会怎样。

**Comment by webleon** [comment]
> 谢谢回复！不知11.5.1安装会怎样。



> 谢谢回复！不知11.5.1安装会怎样。

再看看链接。

**Comment by lrgcx** [comment]
哈哈！谢谢大佬！！

**Comment by lrgcx** [comment]
之前用7070sff的EFI启动时第一次出现进度条的白色苹果图标和第二次进度条的白色苹果图标一样大（分辨率？）用您新发的7070mff的EFI启动时两次败苹果图标不一样大，第一次的小不少。不知能否调整成一样。总之感谢🙏

**Comment by webleon** [comment]
> 之前用7070sff的EFI启动时第一次出现进度条的白色苹果图标和第二次进度条的白色苹果图标一样大（分辨率？）用您新发的7070mff的EFI启动时两次败苹果图标不一样大，第一次的小不少。不知能否调整成一样。总之感谢🙏

Config.plist > NVRAM > 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 > UIScale > 01

**Comment by lrgcx** [comment]
查看了也是和您写的一样 UIScale > 01

**Comment by webleon** [comment]
> 查看了也是和您写的一样 UIScale > 01 从系统启动选项那里开始图标就较小。

换成02
