### ISSUE TITLE
USB2.0 HUB on Dell moniter

### ISSUE THREAD

**Issue by aya4dw** [webleon/Hackintosh-OptiPlex-7070-SFF#15]
The USB2.0 hub on My Dell monitor doesn't work when it's connected to the USB3.0 port, but can work when connected to the USB2.0 port.

**Comment by webleon** [comment]
Due to the 15 ports limit by the MacOS, I blocked USB 2.0 Function of two USB ports right above the Ethernet port.
You can either plug to other ports or re-map your USB ports to meet your needs.
https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html
