### ISSUE TITLE
作者是否能更新到BigSur呢？

### ISSUE THREAD

**Issue by cyg02032015** [webleon/Hackintosh-OptiPlex-7070-SFF#2]

**Comment by webleon** [comment]
最近有时间的话会更新。

**Comment by cyg02032015** [comment]
> 最近有时间的话会更新。

这么快就更新了。 👍👍👍

**Comment by cyg02032015** [comment]
方便添加一下联系方式吗？
我现在用的机型和作者的一模一样 有几个问题想要问一下

**Comment by webleon** [comment]
> 方便添加一下联系方式吗？
> 我现在用的机型和作者的一模一样 有几个问题想要问一下

可以先把你的问题发邮件给我，我看下。

**Comment by cyg02032015** [comment]
没有安装GPU的话是否需要更改某些字段啊？

**Comment by cyg02032015** [comment]
成功安装 666

**Comment by WangBo-cmd** [comment]
看配置和机型和您是一样的，只是您加了张显卡？用OC引导的话，我读条还剩下5分之一的时候就自动重启了，也不知道什么原因，请指教下。
