### ISSUE TITLE
有计划升级到macOS Ventura吗？

### ISSUE THREAD

**Issue by cyg02032015** [webleon/Hackintosh-OptiPlex-7070-SFF#21]

**Comment by aya4dw** [comment]
I updated the opencore to 0.85, Monterey worked well. But it still cannot boot macOS Ventura.
Now I'm expecting WebLeOn to upgrade opencore to support macOS Ventura.

**Comment by cyg02032015** [comment]
> 

try https://github.com/cyg02032015/OptiPlex-7070-SFF

**Comment by cyg02032015** [comment]
> I updated the opencore to 0.85, Monterey worked well. But it still cannot boot macOS Ventura. Now I'm expecting WebLeOn to upgrade opencore to support macOS Ventura.
try https://github.com/cyg02032015/OptiPlex-7070-SFF
