### ISSUE TITLE
5700XT  Black screen

### ISSUE THREAD

**Issue by jinxiangqiang** [webleon/Hackintosh-OptiPlex-7070-SFF#4]
My machine is the same as yours. Could you tell me where to make 5700XT not black screen

**Comment by webleon** [comment]
5700XT in a small form factor machine? It's hard to believe.
Anyway, you can try to add agdpmod=pikera shikigva=80 to boot-args

**Comment by jinxiangqiang** [comment]
Perfect solution. Thank you very much

**Comment by jinxiangqiang** [comment]
I changed the case and the power supply
