### ISSUE TITLE
U630 no 4K support

### ISSUE THREAD

**Issue by dittman1** [webleon/Hackintosh-OptiPlex-7070-SFF#5]
I can't get any higher than 1920x1080 to show up.  I get the 4K resolutions in Windows and I can see it's 4K mode when it starts to boot but then at some point during the boot it switches to FHD.

Trying to figure this out it sounds like I need to make the changes you have listed for GRUB but I don't see how to make those changes.

**Comment by dittman1** [comment]
I found this:  https://github.com/datasone/grub-mod-setup_var/releases

I added modGRUBShell.efi to config.plist and when booting I can select it.  I entered "setup_var 0x8DC 0x02" and "setup_var 0x5BE 0x00" in GRUB and then typed "exit" and it continued to boot but still switched to FHD when the progress bar is about the middle.

**Comment by webleon** [comment]
It's highly recommend to use a separate USB stick with Grub bootloader.

**Comment by dittman1** [comment]
Any idea why after updating DVMT and CFG lock it still refuses to let me use 4K?

**Comment by dittman1** [comment]
I found that I needed to update the config.plist with this:

<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
                        <dict>
                                <key>AAPL,ig-platform-id</key>
                                <data>00009B3E</data>
                                <key>framebuffer-patch-enable</key>
                                <data>01000000</data>
                                <key>framebuffer-con2-enable</key>
                                <data>01000000</data>
                                <key>frambuffer-con2-type</key>
                                <data>00080000</data>
                                <key>framebuffer-stolenmem</key>
                                <data>AAAwAQ==</data>
                        </dict>
